# Generated by Django 2.0.2 on 2018-03-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='author',
            field=models.CharField(max_length=64),
        ),
    ]
