# Generated by Django 2.0.2 on 2018-04-20 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0004_auto_20180420_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
