# Generated by Django 2.0.2 on 2018-04-30 04:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_site', '0005_remove_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='users_liked',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
