# Generated by Django 2.0.3 on 2018-05-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0008_auto_20180512_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='users_liked',
            field=models.ManyToManyField(related_name='news_posts_liked', to='news_site.Profile'),
        ),
    ]
