# Generated by Django 2.0.2 on 2018-05-15 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0008_auto_20180515_0409'),
        ('news_site', '0010_auto_20180513_0022'),
    ]

    operations = [
    ]
