# Generated by Django 2.0.2 on 2018-05-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0011_merge_20180515_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.TextField(default=' ', max_length=25),
        ),
    ]
