# Generated by Django 2.0.2 on 2018-05-19 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0012_profile_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
    ]
