# Generated by Django 2.0.2 on 2018-05-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0014_profile_email_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avitar',
            field=models.IntegerField(choices=[(1, 'Not relevant'), (2, 'Review'), (3, 'Maybe relevant'), (4, 'Relevant'), (5, 'Leading candidate')], default=1),
        ),
    ]
