# Generated by Django 2.0.2 on 2018-05-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0015_profile_avitar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.URLField(default='img/avitar/1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avitar',
            field=models.IntegerField(choices=[(1, 'Soccer Ball'), (2, 'Sunglasses'), (3, 'A Bus')], default=1),
        ),
    ]
