# Generated by Django 2.0.2 on 2018-05-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0016_auto_20180522_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.URLField(default='/img/avitars/1.jpegimg/avitar/1'),
        ),
    ]
