# Generated by Django 2.0.2 on 2018-05-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0020_auto_20180522_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avitar',
            field=models.CharField(choices=[('news_site/static/img/avitars/1.jpeg', 'Soccer Ball'), ('news_site/static/img/avitars/2.jpeg', 'Sunglasses'), ('news_site/static/img/avitars/3.jpeg', 'A Bus')], default='news_site/static/img/avitars/1.jpeg', max_length=200),
        ),
    ]
