# Generated by Django 2.0.2 on 2018-05-22 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0021_auto_20180522_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='user',
            field=models.ForeignKey(default=None, limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avitar',
            field=models.CharField(choices=[('img/avitars/1.jpeg', 'Soccer Ball'), ('img/avitars/2.jpeg', 'Sunglasses'), ('img/avitars/3.jpeg', 'A Bus')], default='img/avitars/1.jpeg', max_length=200),
        ),
    ]
