# Generated by Django 2.0.2 on 2018-05-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0023_auto_20180522_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='article',
            field=models.FileField(default=' ', upload_to='news_atricles/'),
        ),
    ]
