# Generated by Django 2.0.2 on 2018-05-24 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0025_auto_20180524_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='news_site.Comment'),
        ),
    ]
