# Generated by Django 2.0.2 on 2018-05-24 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0026_comment_child'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='child',
            new_name='parent',
        ),
    ]
