# Generated by Django 2.0.2 on 2018-05-26 20:56

from django.db import migrations, models
import news_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0027_auto_20180524_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='featured_img',
            field=models.FileField(default='default', upload_to=news_site.models.attachment_path_with_name_img),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='article',
            field=models.FileField(default=' ', upload_to=news_site.models.attachment_path_with_name),
        ),
    ]
