# Generated by Django 2.0.2 on 2018-05-26 22:44

from django.db import migrations, models
import news_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0029_auto_20180526_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='featured_img',
            field=models.FileField(default='default', upload_to=news_site.models.attachment_path_with_name_img),
        ),
    ]
